export const TABS_TYPES = {
  service: 'service',
  profile: 'profile',
  users: 'users',
  editProfile: 'editProfile',
  organization: 'organization',
};

export const TABS = {
  service: 'service',
  users: 'users',
  Fee: 'Fee',
  visibility: 'visibility',
  reminders: 'reminders',
  recurring: 'recurring',
  availability: 'availability',
  Whiteblacklist: 'Whiteblacklist',
  map: 'map',
  organizations: 'organizations',
  profil: 'profil',
  publications: 'publications',
  education: 'education',
  userProfile: 'user profile',
  jobHistory: 'job history',
  general: 'general',
  social: 'social links',
  email: 'change email',
  members: 'members',
  services: 'services',
  information: 'information',
  pendingJoinRequests: 'pending join requests',
  pendingInvites: 'pending invites',
  roundRobin: 'Round Robin',
  CurrentTeamsAndServices: 'CurrentTeamsAndServices',
  ManageService: 'ManageService',
  ManageTeam: 'ManageTeam',
  roundRobinService: 'roundRobinService',
  searchTabs: 'searchTabs',
  signup: 'signup',
};
export const METHODS_TABS = ['profile', 'service', 'editProfile', 'organization'];
export const SUMMARY_TABS = {
  service: ['Fee', 'visibility', 'recurring', 'availability', 'Whiteblacklist'],
  roundRobinService: ['recurring', 'Security'],
  profileUsers: ['user profile', 'publications', 'education', 'job history'],
  users: ['users', 'organizations'],
  editProfile: ['general', 'social links', 'change email'],
  organizationPublic: ['members', 'services', 'signup'],
  organizationPublicMembers: ['members'],
  organizationManagement: [
    'information',
    'members',
    'services',
    'pending join requests',
    'pending invites',
    'Round Robin',
  ],
  roundRobinManagement: ['CurrentTeamsAndServices', 'ManageService', 'ManageTeam'],
  searchTabs: ['Users', 'Organizations', 'Services', 'Events'],
};
