const ACTIONS = {
  setAvatar: 'SET_AVATAR',
  setName: 'SET_NAME',
  setUsername: 'SET_USERNAME',
  setUsernameURL: 'SET_USERNAME_URL',
  setFullname: 'SET_FULLNAME',
  setPhone: 'SET_PHONE',
  setEmail: 'SET_EMAIL',
  setWebsite: 'SET_WEBSITE',
  setheadline: 'SET_HEADLINE',
  setDescription: 'SET_DESCRIPTION',
  setLocation: 'SET_LOCATION',
  setCountry: 'SET_COUNTRY',
  setVisible: 'SET_VISIBLE',
  setIndividual: 'SET_INDIVIDUAL',
  setTimezone: 'SET_TIMEZONE',
  setLanguage: 'SET_LANGUAGE',
  setFacebook: 'SET_FACEBOOK',
  setLinkedin: 'SET_LINKEDIN',
  setYoutube: 'SET_YOUTUBE',
  setZipCode: 'SET_ZIP_CODE',
  setTwitter: 'SET_TWITTER',
  setInstagram: 'SET_INSTAGRAM',
  setProfileMediaLink: 'SET_PROFILE_MEDIA_LINK',
  setMediaType: 'SET_MEDIA_TYPE',
  setHashtags: 'SET_HASHTAGS',
  setPublicUrl: 'SET_PUBLIC_URL',
  setLatitude: 'SET_LAT',
  setLongitude: 'SET_LONG',
  setProfileBG: 'SET_PROFILE_BG',
};
export default ACTIONS;
